from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import fsi_corpus
from fsi_corpus import Corpus, Record

REPO = fsi_corpus.REPO
EXPORT = Path("specs/fsi/export/corpus.json")
INDEX = Path("docs/FSIregulation.md")
PAGES = Path("docs/regulations")
GENERATED_MARK = "<!-- generated by utils/fsi_render.py; edit specs/fsi/ and run make fsi-render -->"
SCHEMA_VERSION = 1
TOPIC_LABELS = {
    "banking": "Banking",
    "capital-markets": "Capital markets",
    "insurance": "Insurance",
    "payments-consumer": "Payments & consumer protection",
    "digital-assets": "Digital assets",
    "stablecoins": "Stablecoins",
    "operational-resilience": "Operational resilience",
    "cybersecurity": "Cybersecurity",
    "data-protection": "Data protection",
    "healthcare": "Healthcare",
    "aml": "Anti-money laundering & sanctions",
    "whistleblower": "Whistleblower programs",
    "recordkeeping": "Recordkeeping",
}
STATUS_LABELS = {
    "in_force": "in force",
    "enacted": "enacted",
    "proposed": "proposed",
    "not_enacted": "not enacted",
    "withdrawn": "withdrawn",
    "repealed": "repealed",
    "superseded": "superseded",
    "guidance": "guidance",
    "unverified": "status unverified",
}


def page_slug(jurisdiction: str) -> str:
    return jurisdiction.lower()


def duration_months(duration: str) -> int:
    match = re.fullmatch(r"P(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)D)?", duration)
    if not match:
        raise ValueError(duration)
    years, months, days = (int(g) if g else 0 for g in match.groups())
    return years * 12 + months + (1 if days else 0)


def humanize(duration: str) -> str:
    match = re.fullmatch(r"P(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)D)?", duration)
    if not match:
        raise ValueError(duration)
    parts = []
    for value, unit in zip(match.groups(), ("year", "month", "day")):
        if value:
            n = int(value)
            parts.append(f"{n} {unit}{'' if n == 1 else 's'}")
    return " ".join(parts)


def _controls_by_obligation(corpus: Corpus) -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = defaultdict(list)
    for control in sorted(corpus.controls, key=lambda c: c["id"]):
        for obligation in control["satisfies"]:
            mapping[obligation].append(control["id"])
    return mapping


def coverage(corpus: Corpus) -> dict[str, Any]:
    controlled = _controls_by_obligation(corpus)
    instruments = {r["id"]: r for r in corpus.instruments}
    rows: dict[str, dict[str, int]] = {}
    for key in corpus.registry["jurisdictions"]:
        obligations = [o for o in corpus.obligations if instruments[o["instrument"]]["jurisdiction"] == key]
        rows[key] = {
            "instruments": sum(1 for r in corpus.instruments if r["jurisdiction"] == key),
            "obligations": len(obligations),
            "obligations_with_control": sum(1 for o in obligations if controlled.get(o["id"])),
            "unmigrated_references": sum(1 for h in corpus.holdings if h["jurisdiction"] == key),
        }
    confidence: dict[str, dict[str, int]] = {}
    for layer, records in (("instruments", corpus.instruments), ("obligations", corpus.obligations), ("controls", corpus.controls)):
        counts = {level: 0 for level in ("high", "medium", "low")}
        for record in records:
            counts[record["confidence"]] += 1
        confidence[layer] = counts
    links = {state: 0 for state in ("ok", "blocked", "broken")}
    for holding in corpus.holdings:
        links[holding["link"]["status"]] += 1
    return {
        "by_jurisdiction": rows,
        "confidence": confidence,
        "unmigrated_link_status": links,
        "obligations_without_control": sorted(o["id"] for o in corpus.obligations if not controlled.get(o["id"])),
    }


def build_export(corpus: Corpus) -> dict[str, Any]:
    controlled = _controls_by_obligation(corpus)
    by_instrument: dict[str, list[str]] = defaultdict(list)
    obligations = []
    for record in sorted(corpus.obligations, key=lambda o: o["id"]):
        by_instrument[record["instrument"]].append(record["id"])
        item = dict(record)
        item["controls"] = controlled.get(record["id"], [])
        retention = record.get("retention")
        if retention and retention.get("period"):
            item["retention"] = {**retention, "period_months": duration_months(retention["period"])}
        obligations.append(item)
    instruments = [
        {**record, "obligations": by_instrument.get(record["id"], [])}
        for record in sorted(corpus.instruments, key=lambda r: r["id"])
    ]
    dates = [r["verified"]["date"] for r in corpus.instruments + corpus.obligations + corpus.controls]
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_by": "utils/fsi_render.py",
        "verified_through": max(dates) if dates else None,
        "registry": corpus.registry,
        "instruments": instruments,
        "obligations": obligations,
        "controls": sorted(corpus.controls, key=lambda c: c["id"]),
        "unmigrated_references": corpus.holdings,
        "coverage": coverage(corpus),
    }


def _link(title: str, url: str) -> str:
    return f"[{title.replace('[', '(').replace(']', ')')}]({url})"


def _blockquote(text: str) -> str:
    return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())


def _retention_line(retention: Record) -> str:
    if retention.get("indefinite"):
        head = "Indefinite"
    elif retention.get("period"):
        head = humanize(retention["period"])
    else:
        head = "Accessibility window only"
    extras = []
    if retention.get("accessible_period"):
        extras.append(f"readily accessible for the first {humanize(retention['accessible_period'])}")
    if retention.get("extended_period"):
        extras.append(f"up to {humanize(retention['extended_period'])} if the authority requests it")
    extra = f"; {'; '.join(extras)}" if extras else ""
    return f"**{head}**{extra}. Trigger: {retention['trigger']}"


def _banner(title: str, lede: str, up: str) -> list[str]:
    return [
        GENERATED_MARK,
        f"# {title}",
        "",
        (
            f"> **Generated file. Do not edit it by hand.** The source of record is [`specs/fsi/`]({up}specs/fsi/). "
            "Regenerate with `make fsi-render`. CI fails if this file drifts from the corpus."
        ),
        "",
        lede,
        "",
    ]


def render_index(corpus: Corpus) -> str:
    registry = corpus.registry
    cov = coverage(corpus)
    instruments = sorted(corpus.instruments, key=lambda r: (r["jurisdiction"], r["id"]))
    by_instrument: dict[str, list[Record]] = defaultdict(list)
    for obligation in corpus.obligations:
        by_instrument[obligation["instrument"]].append(obligation)

    lines = _banner(
        "Financial Services Regulatory Corpus",
        "Recordkeeping and auditability obligations for regulated financial workloads, with the controls that "
        "implement them on AWS. Every period stated here is quoted verbatim from the primary source it cites. "
        "Each record carries a confidence level, the date it was verified, and a date by which it must be re-verified. "
        "Once that date passes, the build fails. This is engineering reference material, not legal advice.",
        "../",
    )
    lines += [
        (
            "Machine-readable export: [`specs/fsi/export/corpus.json`](../specs/fsi/export/corpus.json). "
            "Example: `jq '[.obligations[] | select(.retention.period_months) | {id, months: .retention.period_months}] "
            "| sort_by(-.months)' specs/fsi/export/corpus.json`."
        ),
        "",
        "## How to read confidence",
        "",
        "| Level | Meaning |",
        "|---|---|",
        "| high | The current primary text was read, and every quoted number was compared against it verbatim. |",
        "| medium | The primary text was read, but either its currency is unconfirmed (for example the original Official Journal text rather than the consolidated version) or the record is design guidance rather than law. |",
        "| low | Allowed for instruments only, and none currently carry it. Unmigrated references have not been read, so they carry no confidence level at all. |",
        "",
        "## Coverage",
        "",
        "| Jurisdiction | Instruments | Obligations | Obligations with a control | Unmigrated references |",
        "|---|---:|---:|---:|---:|",
    ]
    for key, row in cov["by_jurisdiction"].items():
        if not any(row.values()):
            continue
        lines.append(
            f"| {registry['jurisdictions'][key]['name']} | {row['instruments']} | {row['obligations']} "
            f"| {row['obligations_with_control']} | {row['unmigrated_references']} |"
        )
    link_status = cov["unmigrated_link_status"]
    lines += [
        "",
        (
            f"Unmigrated reference links at their last check: {link_status['ok']} resolved, {link_status['blocked']} "
            f"refused automated checks, and {link_status['broken']} {'was' if link_status['broken'] == 1 else 'were'} dead."
        ),
        "",
        "## Instruments",
        "",
        "| Instrument | Jurisdiction | Status | Obligations | Confidence | Review due |",
        "|---|---|---|---:|---|---|",
    ]
    for record in instruments:
        anchor = f"regulations/{page_slug(record['jurisdiction'])}.md#{record['id']}"
        lines.append(
            f"| [{record['short']}]({anchor}) — {record['title'].split(' — ', 1)[-1]} | {record['jurisdiction']} "
            f"| {STATUS_LABELS[record['status']]} (as of {record['status_as_of']}) | {len(by_instrument[record['id']])} "
            f"| {record['confidence']} | {record['review_due']} |"
        )
    lines += [
        "",
        "## Retention periods, longest first",
        "",
        "| Period | Accessible | Obligation | Applies to | Citation |",
        "|---|---|---|---|---|",
    ]
    instrument_map = {r["id"]: r for r in corpus.instruments}

    def sort_key(o: Record) -> tuple[int, str]:
        retention = o["retention"]
        if retention.get("indefinite"):
            return (-10**6, o["id"])
        return (-duration_months(retention.get("period") or retention["accessible_period"]), o["id"])

    for obligation in sorted((o for o in corpus.obligations if o.get("retention")), key=sort_key):
        retention = obligation["retention"]
        if retention.get("indefinite"):
            period = "Indefinite"
        elif retention.get("period"):
            period = humanize(retention["period"])
        else:
            period = "—"
        if retention.get("extended_period"):
            period += f" (up to {humanize(retention['extended_period'])})"
        accessible = humanize(retention["accessible_period"]) if retention.get("accessible_period") else "—"
        instrument = instrument_map[obligation["instrument"]]
        anchor = f"regulations/{page_slug(instrument['jurisdiction'])}.md#{obligation['id'].replace('.', '-')}"
        lines.append(
            f"| {period} | {accessible} | [{obligation['title']}]({anchor}) | {obligation['applies_to']} "
            f"| {obligation['source']['citation']} |"
        )
    lines += [
        "",
        "## Unmigrated references",
        "",
        (
            "These entries were carried over from the link list this file used to be. They are not instruments yet: "
            "nobody has read them into obligations, so they assert nothing beyond the page they point at. The move "
            "corrected their jurisdiction, authority host, legislative status and dead links, and every correction "
            "is recorded against the entry in `specs/fsi/holding.yaml`. Migration proceeds one cluster at a time."
        ),
        "",
    ]
    grouped: dict[str, dict[str, list[Record]]] = defaultdict(lambda: defaultdict(list))
    for holding in corpus.holdings:
        grouped[holding["jurisdiction"]][holding["topic"]].append(holding)
    for key in registry["jurisdictions"]:
        if key not in grouped:
            continue
        lines += [f"### {registry['jurisdictions'][key]['name']}", ""]
        for topic, label in TOPIC_LABELS.items():
            entries = grouped[key].get(topic)
            if not entries:
                continue
            lines += [f"#### {label}", ""]
            for holding in entries:
                if holding["link"]["status"] == "broken":
                    item = f"- {holding['title']} — **dead link** (last checked {holding['link']['checked']})"
                else:
                    item = f"- {_link(holding['title'], holding['url'])}"
                tags = []
                if holding.get("status"):
                    tags.append(f"**{STATUS_LABELS[holding['status']]}**")
                if holding["link"]["status"] == "blocked":
                    tags.append("site refuses automated link checks")
                if tags:
                    item += f" — {'; '.join(tags)}"
                lines.append(item)
                if holding.get("status_note"):
                    lines.append(f"  <br>{holding['status_note']}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_jurisdiction(corpus: Corpus, jurisdiction: str) -> str:
    registry = corpus.registry
    controlled = _controls_by_obligation(corpus)
    instruments = sorted((r for r in corpus.instruments if r["jurisdiction"] == jurisdiction), key=lambda r: r["id"])
    ids = {r["id"] for r in instruments}
    obligations = [o for o in corpus.obligations if o["instrument"] in ids]
    obligation_ids = {o["id"] for o in obligations}
    name = registry["jurisdictions"][jurisdiction]["name"]
    lines = _banner(
        f"{name} — recordkeeping obligations",
        f"Instruments, obligations and controls for {name}. The index is [`FSIregulation.md`](../FSIregulation.md).",
        "../../",
    )
    for instrument in instruments:
        authority = registry["authorities"][instrument["authority"]]["name"]
        lines += [
            f'<a id="{instrument["id"]}"></a>',
            "",
            f"## {instrument['title']}",
            "",
            instrument["summary"],
            "",
            f"- **Citation:** {_link(instrument['citation'], instrument['url'])} ({authority})",
            f"- **Status:** {STATUS_LABELS[instrument['status']]} as of {instrument['status_as_of']}",
        ]
        if instrument.get("status_note"):
            lines.append(f"- **Status note:** {instrument['status_note']}")
        if instrument.get("applies_to"):
            lines.append(f"- **Applies to:** {instrument['applies_to']}")
        lines += [
            f"- **Cloud relevance:** {instrument['cloud_relevance']}",
            (
                f"- **Confidence:** {instrument['confidence']}. Verified {instrument['verified']['date']} by "
                f"{instrument['verified']['by']}. {instrument['verified']['method']}"
            ),
            f"- **Review due:** {instrument['review_due']}",
            "",
        ]
        for obligation in sorted((o for o in obligations if o["instrument"] == instrument["id"]), key=lambda o: o["id"]):
            source = obligation["source"]
            lines += [
                f'<a id="{obligation["id"].replace(".", "-")}"></a>',
                "",
                f"### {obligation['title']}",
                "",
                f"`{obligation['id']}` · {obligation['kind']} · applies to {obligation['applies_to']}",
                "",
                obligation["requirement"],
                "",
            ]
            if obligation.get("retention"):
                lines += [f"- **Retention:** {_retention_line(obligation['retention'])}"]
            lines.append(
                f"- **Source:** {_link(source['citation'], source['url'])}, retrieved {source['retrieved']}"
                + (f" ({source['text_as_of']})" if source.get("text_as_of") else "")
            )
            if obligation.get("note"):
                lines.append(f"- **Note:** {obligation['note']}")
            if obligation.get("see_also"):
                related = ", ".join(f"`{other}`" for other in obligation["see_also"])
                lines.append(f"- **See also:** {related}")
            linked = controlled.get(obligation["id"], [])
            if linked:
                lines.append("- **Controls:** " + ", ".join(f"[{cid}](#{cid})" for cid in linked))
            else:
                lines.append("- **Controls:** none yet")
            lines += [
                f"- **Confidence:** {obligation['confidence']}; review due {obligation['review_due']}",
                "",
                _blockquote(source["quote"]),
                "",
            ]
    relevant = [c for c in sorted(corpus.controls, key=lambda c: c["id"]) if obligation_ids & set(c["satisfies"])]
    if relevant:
        lines += ["## Controls", ""]
    for control in relevant:
        satisfied = [o for o in control["satisfies"] if o in obligation_ids]
        lines += [
            f'<a id="{control["id"]}"></a>',
            "",
            f"### {control['title']}",
            "",
            f"`{control['id']}` · {control['kind']} · confidence {control['confidence']} · review due {control['review_due']}",
            "",
            control["implementation"],
            "",
            "- **Satisfies here:** " + ", ".join(f"[`{o}`](#{o.replace('.', '-')})" for o in satisfied),
            "- **Evidence:**",
        ]
        lines += [f"  - {item}" for item in control["evidence"]]
        if control["aws"]:
            lines.append("- **AWS:**")
            for binding in control["aws"]:
                lines.append(f"  - {_link(binding['service'], binding['doc'])}: {binding['configuration']}")
                if binding.get("quote"):
                    lines.append(f"    <br>*AWS documentation:* “{binding['quote']}”")
        if control.get("limits"):
            lines.append(f"- **Limits:** {control['limits']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def outputs(corpus: Corpus) -> dict[Path, str]:
    result: dict[Path, str] = {
        EXPORT: json.dumps(build_export(corpus), indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        INDEX: render_index(corpus),
    }
    for jurisdiction in sorted({r["jurisdiction"] for r in corpus.instruments}):
        result[PAGES / f"{page_slug(jurisdiction)}.md"] = render_jurisdiction(corpus, jurisdiction)
    return result


def _stale_pages(repo: Path, expected: dict[Path, str]) -> list[Path]:
    stale = []
    for path in sorted((repo / PAGES).glob("*.md")):
        rel = path.relative_to(repo)
        if rel not in expected and path.read_text(encoding="utf-8").startswith(GENERATED_MARK):
            stale.append(rel)
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the FSI corpus to its export and markdown pages.")
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from the corpus")
    parser.add_argument("--repo", type=Path, default=REPO)
    parser.add_argument("--today", type=dt.date.fromisoformat, default=None)
    args = parser.parse_args(argv)
    corpus, findings = fsi_corpus.validate(args.repo / "specs" / "fsi", args.today)
    if findings:
        for finding in findings:
            sys.stdout.write(f"{finding}\n")
        sys.stdout.write("fsi render refused: the corpus does not validate\n")
        return 1
    expected = outputs(corpus)
    stale = _stale_pages(args.repo, expected)
    if args.check:
        drift = [
            rel for rel, content in expected.items()
            if not (args.repo / rel).exists() or (args.repo / rel).read_text(encoding="utf-8") != content
        ]
        for rel in drift + stale:
            sys.stdout.write(f"{rel}: out of date with specs/fsi/\n")
        if drift or stale:
            sys.stdout.write("run `make fsi-render` and commit the result\n")
            return 1
        sys.stdout.write(f"fsi generated files up to date ({len(expected)} files)\n")
        return 0
    for rel, content in expected.items():
        target = args.repo / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        sys.stdout.write(f"wrote {rel}\n")
    for rel in stale:
        (args.repo / rel).unlink()
        sys.stdout.write(f"removed stale {rel}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
